services:
  chrome:
    image: selenium/node-chrome:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - NOVNC=true
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NO_VNC_PORT=7900
    ports:
      - "6900:5900"
      - "7900:7900"

  edge:
    image: selenium/node-edge:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - NOVNC=true
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NO_VNC_PORT=7901
    ports:
      - "6901:5900"
      - "7901:7900"

  firefox:
    image: selenium/node-firefox:4.0.0-rc-2-prerelease-20210908
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - NOVNC=true
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NO_VNC_PORT=7902
    ports:
      - "6902:5900"
      - "7902:7900"

  selenium-hub:
    image: selenium/hub:4.0.0-rc-2-prerelease-20210908
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    links:
    - candidato